import Navbar from "@/components/Navbar";
import Link from "next/link";

export const metadata = {
  title: "Terms of Service - Prismiq",
  description: "Terms and conditions for using Prismiq.",
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="relative z-10 max-w-2xl mx-auto px-6 pt-28 pb-20">
        <div className="mb-8">
          <Link href="/" className="text-xs text-white/30 hover:text-white/60 transition-colors">← Back to Prismiq</Link>
        </div>

        <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-white/30 text-sm mb-10">Last updated: May 2025</p>

        <div className="space-y-8 text-white/60 text-sm leading-relaxed">

          <section>
            <h2 className="text-white font-semibold text-base mb-3">1. The service</h2>
            <p>Prismiq ("we", "us") provides an AI-powered content understanding tool that summarizes YouTube videos, websites, PDFs, and images. By using Prismiq, you agree to these terms.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">2. Free tier</h2>
            <p>Unregistered users get 2 free scans. Signing in with Google gives 2 additional scans. Free registered accounts receive 4 scans per 24-hour period. Free scans are for personal, non-commercial use.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">3. Paid plans</h2>
            <p>Paid subscriptions (Starter, Pro, Unlimited) are billed monthly through Gumroad. You can cancel at any time and your access continues until the end of the billing period. We do not offer partial refunds for unused time, but we will consider refund requests made within 7 days of a charge.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">4. Acceptable use</h2>
            <p>You may not use Prismiq to:</p>
            <ul className="mt-2 space-y-2 list-none">
              {[
                "Process content that violates copyright in ways that go beyond fair use",
                "Scrape or resell AI-generated outputs at scale without permission",
                "Attempt to reverse engineer, abuse, or overload our systems",
                "Submit content that is illegal or harmful",
              ].map(item => (
                <li key={item} className="flex gap-2"><span className="text-violet-400 shrink-0">·</span>{item}</li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">5. AI-generated content</h2>
            <p>Summaries and notes are generated by AI and may contain errors. Prismiq is a productivity tool and should not be used as the sole source for important decisions. Always verify information with the original source.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">6. Availability</h2>
            <p>We aim for high uptime but do not guarantee uninterrupted service. We may change, suspend, or discontinue any part of the service at any time. In the case of discontinuation, we will notify paid users and offer a prorated refund.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">7. Limitation of liability</h2>
            <p>Prismiq is provided "as is". We are not liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability is limited to the amount you paid in the last 30 days.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">8. Changes to these terms</h2>
            <p>We may update these terms. Continued use of Prismiq after changes means you accept the updated terms. We will notify active paid users of material changes by email.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-3">9. Contact</h2>
            <p>Questions? Email us at <a href="mailto:shopatmine01@gmail.com" className="text-violet-400 hover:underline">shopatmine01@gmail.com</a>.</p>
          </section>

        </div>
      </main>
    </>
  );
}
